capabilities:
  allowlist: []     # empty = all enabled pass (except denylist)
  denylist: []
  registry:
    - id: hs-tree
      module: pefc.capabilities.handlers.hstree:HSTreeHandler
      enabled: true
      params: {}
    - id: opa-rego
      module: pefc.capabilities.handlers.opa:OPAHandler
      enabled: true
      params: 
        policy_dir: "policies"
        query: "data.pefc.allow"
    - id: ids-synth
      module: pefc.capabilities.handlers.ids:IDSHandler
      enabled: true
      params: 
        n_seeds: 24
routing:
  defaults:
    # optional: orders or future overrides
  by_type:
    security.policy.violation: [opa-rego, hs-tree]
    robustness.fuzz: [ids-synth]
