name: Gate Merge

on:
  pull_request:
    branches: [ "main" ]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa && sudo mv opa /usr/local/bin/opa
      - name: Install deps
        run: pip install -r requirements.txt || true
      - name: Run demo
        run: make demo || make regtech-demo || true
      - name: Assert thresholds
        run: python scripts/assert_thresholds.py out/metrics.json
      - name: Upload metrics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr_metrics
          path: out/**
