name: Metrics Rollup

on:
  schedule: 
    - cron: "0 3 * * MON"
  workflow_dispatch:

jobs:
  rollup:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
      - run: pip install pandas numpy scipy jq
      - name: Rollup metrics
        run: |
          python scripts/metrics_rollup.py out/ rollup/metrics-weekly.json || true
      - name: Commit rollup
        run: |
          mkdir -p rollup
          git add rollup/metrics-weekly.json || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: weekly metrics rollup" || echo "No changes"
          git push || true
