name: Nightly Bench

on:
  schedule: 
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa && sudo mv opa /usr/local/bin/opa
      - run: pip install -r requirements.txt
      - name: Run demo
        run: make demo || make regtech-demo || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly_bench
          path: |
            out/**
            orchestrator/journal/J.jsonl
            out/journal/merkle.txt
          if-no-files-found: warn
      - name: Job summary
        run: |
          echo "## Nightly Bench Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f out/metrics.json ]; then
            jq -r '. as $m | "coverage_gain=\($m.coverage.coverage_gain)\nnovelty.avg=\($m.novelty.avg)\nmdl.compression=\($m.mdl_proxy.compression)\ndelta.local=\($m.delta.local)\nincidents=\($m.incidents.total)\naudit_cost.ms=\($m.audit_cost.simulated_ms)"' out/metrics.json >> $GITHUB_STEP_SUMMARY
          else
            echo "No metrics.json produced" >> $GITHUB_STEP_SUMMARY
          fi
