name: Release

on:
  workflow_dispatch:
    inputs:
      version: 
        description: "Semver tag e.g. v0.1.1"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3
      - name: Install Syft/Grype
        uses: anchore/sbom-action/download-syft@v0
      - uses: anchore/scan-action/download-gh-release@v3
        with: 
          release: "v0.78.0"
      - name: Build hermetic image
        run: |
          docker build --no-cache --pull -t ghcr.io/${{github.repository}}:${{ github.event.inputs.version }} -f Dockerfile .
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ghcr.io/${{github.repository}}:${{ github.event.inputs.version }}
      - name: Generate SBOM
        run: syft ghcr.io/${{github.repository}}:${{ github.event.inputs.version }} -o spdx-json > sbom.json
      - name: Scan vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/${{github.repository}}:${{ github.event.inputs.version }}
          fail-build: true
          severity-cutoff: high
      - name: Sign image (keyless)
        env: 
          COSIGN_EXPERIMENTAL: "1"
        run: cosign sign --yes ghcr.io/${{github.repository}}:${{ github.event.inputs.version }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Discovery Engine 2-Cat ${{ github.event.inputs.version }}
          files: |
            sbom.json
          generate_release_notes: true